### PR TITLE
feat: add chiadapter

### PR DESCRIPTION
**Pull request by xqbumu**
add chi adapter with test and example.

### CODE REVIEW

**Review by deancn — COMMENTED** [review]
Nice!   @yugasun Can you help review ?

**Comment by yugasun** [comment]
Well done~

**Comment by yugasun** [comment]
@deancn @xqbumu Version `v1.0.1` had been released.

**Comment by deancn** [comment]
@yugasun  thank you so much.

**Comment by yugasun** [comment]
@deancn Star and Issue is welcome~

**Pull request merged**
